import React from 'react'

export default function Dashboard() {
  return (
   <div className='mt-5 pt-5'>Dashboard
  sssssssssssssss  Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae est debitis architecto ipsum. Velit veniam inventore quidem minima accusamus? Reiciendis eligendi cum facilis doloribus cumque dolor ex, aut perspiciatis modi esse numquam aliquam, id nulla harum ea? Autem corrupti tenetur iusto tempore voluptate nihil perferendis, asperiores ex obcaecati sapiente accusantium recusandae eligendi beatae laudantium placeat, necessitatibus vitae fuga, similique delectus amet eius? Ea quisquam, culpa dolores minus quis ullam laboriosam impedit voluptates recusandae illum sunt doloribus amet unde odio tempora porro architecto error ut sapiente iusto perspiciatis fugiat beatae consequatur! Doloribus cum quam quasi eligendi ratione nam consequatur neque odio fugit totam in dignissimos praesentium, fuga mollitia fugiat deserunt soluta veniam cupiditate optio? Dicta voluptatem, harum ab laborum commodi dignissimos ut molestias minus. Porro neque nulla placeat. Delectus cum minus eum voluptas, eaque ut, fuga labore placeat, unde sunt odio distinctio officia asperiores corporis neque sint numquam! Corrupti recusandae ipsa dolor distinctio vitae voluptatem! Mollitia, facere? Repellendus dolor corporis quidem cumque quasi, molestiae molestias ut, repudiandae, dolores accusamus iure voluptatibus. Dolore voluptates tenetur cum vel porro velit, sit accusamus est, enim cupiditate iusto itaque maiores dolorum quam consequuntur quibusdam a delectus quasi quia omnis obcaecati commodi? Similique itaque rerum iure odit, aliquid magni. Non, possimus molestias eos, eius temporibus iure hic mollitia cupiditate dolore asperiores quibusdam fugit tenetur tempore, perspiciatis ut deserunt reiciendis nam in qui ad. Vero excepturi natus quia laboriosam dolores omnis dolorum aliquam odio quibusdam, vel eligendi sit totam ducimus veritatis fugit dolorem quidem expedita. Ducimus, ratione. Corporis perferendis non alias pariatur facere ad neque velit adipisci praesentium, maxime fugiat ut repellat ea harum omnis. Aspernatur accusantium blanditiis, aliquid iure ad soluta placeat ipsam expedita ipsum cum explicabo? Eaque praesentium expedita corporis labore similique reiciendis? Dolores possimus voluptate ipsa quisquam, velit suscipit. Iure nam sed iusto quisquam?
    </div>
  )
}
